In [7]:
import pandas as pd

In [13]:
orders = pd.read_excel("../data/orders.xlsx")
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3323 entries, 0 to 3322
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       3323 non-null   int64
 1   accepted_at    3323 non-null   datetime64[us]
 2   product_id     3323 non-null   int64
 3   quantity       3323 non-null   int64
 4   regular_price  3323 non-null   int64
 5   price          3323 non-null   int64
 6   cost_price     3323 non-null   int64
dtypes: datetime64[us](1), int64(6)
memory usage: 181.9 KB

In [15]:
orders.sample(10)

,order_id,accepted_at,product_id,quantity,regular_price,price,cost_price
1594,1517602948,2022-01-13 22:03:55,7360,1,379,325,221
961,1517488647,2022-01-13 14:59:17,8496,1,79,79,44
1511,1517351210,2022-01-13 13:10:29,26855,1,119,119,77
351,1517664335,2022-01-13 20:08:28,2843,1,99,99,84
1849,1517521940,2022-01-13 17:16:40,60411,1,177,177,96
2119,1517480706,2022-01-13 22:00:22,9424,1,35,35,18
1182,1517479385,2022-01-13 12:51:39,12798,1,159,139,111
17,1517673448,2022-01-13 22:43:27,8490,1,245,169,139
412,1517329328,2022-01-13 12:34:17,20040,1,165,165,93
2015,1517552096,2022-01-13 17:51:30,8057,1,309,309,186

In [17]:
products = pd.read_excel("../data/products.xlsx")
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 40152 entries, 0 to 40151
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  40152 non-null  int64
 1   level1      40152 non-null  str
 2   level2      40152 non-null  str
 3   name        39940 non-null  str
dtypes: int64(1), str(3)
memory usage: 1.2 MB

In [51]:
nan_names = products[products['name'].isna()]['product_id']

orders[orders['product_id'].isin(nan_names)]

,order_id,accepted_at,product_id,quantity,regular_price,price,cost_price
851,1517712881,2022-01-13 14:12:07,7905,1,96,96,58
852,1517514900,2022-01-13 16:48:19,7905,1,96,96,58
1829,1517515168,2022-01-13 14:26:22,13843,2,47,47,27
2668,1517550708,2022-01-13 19:32:35,4758,2,165,165,92
2669,1517518166,2022-01-13 16:52:52,4758,1,165,165,92
2670,1517663284,2022-01-13 14:53:35,4758,1,165,165,92
3231,1517418098,2022-01-13 15:21:15,8139,1,180,180,104
3232,1517332171,2022-01-13 19:33:33,8139,1,180,180,104

In [28]:
orders['accepted_at'].describe()

count                          3323
mean     2022-01-13 16:02:37.557628
min             2022-01-13 08:00:30
25%             2022-01-13 12:50:33
50%             2022-01-13 16:26:22
75%             2022-01-13 19:22:00
max             2022-01-13 22:58:29
Name: accepted_at, dtype: object

In [43]:
products['level1'].nunique()

33