In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
orders = pd.read_excel("../data/orders.xlsx")
products = pd.read_excel("../data/products.xlsx")
sales = orders.merge(products, on="product_id")

#### ABC analysis at the subcategory (level2) level

In [3]:
subcategories_summary = (
    sales
    .groupby('level2')[['quantity', 'price']]
    .sum()
    .reset_index()
    .rename(columns={'price': 'revenue'})
)

In [4]:
subcategories_summary.sample(3)

                 level2  quantity  revenue
8          Все для суши         9     1265
44  Мука и мучные смеси        19     1046
15      Женская гигиена        17     3003

In [5]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

from src.abc_analysis import abc_analysis

In [6]:
bins = [0, 0.25, 0.8, 1]

subcategories_summary['quantity_contribution'], subcategories_summary['quantity_labels'] = abc_analysis(subcategories_summary['quantity'], bins=bins)
subcategories_summary['revenue_contribution'], subcategories_summary['revenue_labels']  = abc_analysis(subcategories_summary['revenue'], bins=bins)

In [9]:
subcategories_summary['quantity_labels'].value_counts()

quantity_labels
C    69
B    26
A     4
Name: count, dtype: int64

In [10]:
subcategories_summary['revenue_labels'].value_counts()

revenue_labels
C    69
B    27
A     4
Name: count, dtype: int64

In [12]:
subcategories_summary.sort_values(by=['quantity_labels', 'revenue_labels'], ascending=[True, True]).head(15)

,level2,quantity,revenue,quantity_contribution,quantity_labels,revenue_contribution,revenue_labels
10,Готовые блюда,248,36944,0.133976,A,0.095100,A
51,Напитки,252,18320,0.067524,A,0.192202,A
72,Снэки соленые,180,15178,0.240622,A,0.318331,B
92,Хлеб и хлебобулочные изделия,218,12722,0.192390,A,0.420119,B
50,Мясо птицы охлажденное,90,19402,0.534030,B,0.145044,A
85,"Тепличные овощи, грибы",105,17782,0.482047,B,0.237976,A
0,"Бананы, косточковые и прочие плоды",76,8929,0.618703,B,0.554217,B
3,Бумажная продукция,42,4134,0.739550,B,0.746244,B
6,Воды питьевые,162,5807,0.284030,B,0.702998,B
18,Замороженные полуфабрикаты,73,13283,0.638264,B,0.387370,B
26,Кисломолочные традиционные продукты,106,7445,0.453912,B,0.656259,B
27,Колбасы,57,11638,0.686227,B,0.450077,B
33,"Корнеплоды, зелень и прочие овощи",157,13537,0.326099,B,0.353178,B
40,Молоко и сливки,147,11400,0.365488,B,0.479422,B
41,Молочно-десертные продукты,116,4261,0.396570,B,0.713967,B